# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADVERTISER_MAPPING',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advertiser_HASH_ID', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=1000)),
                ('Tracking_Link', models.CharField(max_length=1000)),
                ('Preview_Link', models.CharField(max_length=1000)),
                ('Description', models.CharField(max_length=1000)),
                ('Countries', models.CharField(max_length=1000)),
                ('Logo', models.CharField(max_length=1000)),
                ('Privacy', models.CharField(max_length=1000)),
                ('Status', models.CharField(max_length=1000)),
                ('Revenue', models.CharField(max_length=1000)),
                ('Payout', models.CharField(max_length=1000)),
                ('Creative_Urls', models.CharField(max_length=1000)),
                ('Caps', models.CharField(max_length=1000)),
                ('Freshness', models.CharField(max_length=1000)),
                ('Strict_Or_Not', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'ADVERTISER_MAPPING',
            },
        ),
    ]
