# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-27 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADVERTISER_MAPPING', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiser_mapping',
            options={'verbose_name_plural': 'ADVERTISER'},
        ),
    ]
