# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-28 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADVERTISER_MAPPING', '0003_auto_20181027_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='CREATE_API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
