# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-28 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADVERTISER_MAPPING', '0004_create_api'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create_api',
            options={'verbose_name_plural': 'MANUAL API CALL'},
        ),
        migrations.AddField(
            model_name='create_api',
            name='Select_Advertiser_Name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
