# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-28 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADVERTISER_MAPPING', '0005_auto_20181028_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CREATE_API',
        ),
    ]
